import { defineField, defineType } from 'sanity';
import { EXPERIENCE_LEVEL_OPTIONS, FEATURED_SLOT_OPTIONS, TOPIC_OPTIONS } from './constants';

export default defineType({
  name: 'program',
  title: 'Program',
  type: 'document',
  groups: [
    { name: 'content', title: 'Content', default: true },
    { name: 'metadata', title: 'Library Metadata' },
    { name: 'relations', title: 'Related & Downloads' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'content',
      options: { source: 'title', maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'summary',
      title: 'Summary',
      type: 'text',
      rows: 3,
      group: 'content',
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'content',
      options: {
        list: [
          { title: 'Available', value: 'available' },
          { title: 'Coming soon', value: 'comingSoon' },
          { title: 'Paid', value: 'paid' },
        ],
        layout: 'radio',
      },
      initialValue: 'comingSoon',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'frequency',
      title: 'Frequency',
      type: 'string',
      group: 'content',
      description: 'e.g. 2x/week',
    }),
    defineField({
      name: 'sessions',
      title: 'Sessions per week',
      type: 'number',
      group: 'content',
      validation: (rule) => rule.min(1).max(7),
    }),
    defineField({
      name: 'split',
      title: 'Split',
      type: 'string',
      group: 'content',
      description: 'e.g. Full Body, Upper / Lower',
    }),
    defineField({
      name: 'coverImage',
      title: 'Cover image',
      type: 'image',
      group: 'content',
      description:
        'Shown on the library featured card and resource listings. Falls back to the site default if empty.',
      options: { hotspot: true },
    }),
    defineField({
      name: 'overviewImage',
      title: 'Overview image',
      type: 'image',
      group: 'content',
      description:
        'Optional visual overview of the program (e.g. a workout A/B split infographic). Shown on the program page when provided.',
      options: { hotspot: true },
      fields: [
        defineField({
          name: 'alt',
          title: 'Alternative text',
          type: 'string',
          description: 'Describe the image for accessibility.',
        }),
        defineField({
          name: 'caption',
          title: 'Caption',
          type: 'string',
          description: 'Optional note shown below the image.',
        }),
      ],
    }),
    defineField({
      name: 'days',
      title: 'Days',
      type: 'array',
      group: 'content',
      of: [{ type: 'programDay' }],
    }),
    defineField({
      name: 'isFree',
      title: 'Free program',
      type: 'boolean',
      group: 'content',
      initialValue: true,
    }),
    defineField({
      name: 'stripePriceId',
      title: 'Stripe Price ID',
      type: 'string',
      group: 'content',
      description: 'Optional. Used when selling paid programs via Stripe Checkout.',
      hidden: ({ document }) => document?.isFree === true,
    }),
    defineField({
      name: 'topics',
      title: 'Topics',
      type: 'array',
      group: 'metadata',
      of: [{ type: 'string' }],
      options: { list: TOPIC_OPTIONS },
    }),
    defineField({
      name: 'experienceLevel',
      title: 'Experience level',
      type: 'string',
      group: 'metadata',
      options: { list: EXPERIENCE_LEVEL_OPTIONS, layout: 'radio' },
    }),
    defineField({
      name: 'equipment',
      title: 'Equipment',
      type: 'array',
      group: 'metadata',
      of: [{ type: 'string' }],
    }),
    defineField({
      name: 'goal',
      title: 'Goal',
      type: 'string',
      group: 'metadata',
      description: 'e.g. Build muscle, Improve endurance',
    }),
    defineField({
      name: 'durationWeeks',
      title: 'Duration (weeks)',
      type: 'number',
      group: 'metadata',
      validation: (rule) => rule.min(1).max(52),
    }),
    defineField({
      name: 'featured',
      title: 'Featured',
      type: 'boolean',
      group: 'metadata',
      initialValue: false,
    }),
    defineField({
      name: 'featuredSlot',
      title: 'Featured slot',
      type: 'string',
      group: 'metadata',
      options: { list: FEATURED_SLOT_OPTIONS },
    }),
    defineField({
      name: 'popularityScore',
      title: 'Popularity score',
      type: 'number',
      group: 'metadata',
      initialValue: 0,
    }),
    defineField({
      name: 'faq',
      title: 'FAQ',
      type: 'array',
      group: 'relations',
      of: [{ type: 'faqItem' }],
    }),
    defineField({
      name: 'relatedResources',
      title: 'Related resources',
      type: 'array',
      group: 'relations',
      of: [{ type: 'reference', to: [{ type: 'article' }, { type: 'program' }] }],
    }),
    defineField({
      name: 'pdfFile',
      title: 'Downloadable PDF',
      type: 'file',
      group: 'relations',
      options: { accept: 'application/pdf' },
    }),
  ],
  preview: {
    select: {
      title: 'title',
      status: 'status',
      frequency: 'frequency',
      media: 'coverImage',
    },
    prepare({ title, status, frequency, media }) {
      return {
        title,
        subtitle: [status, frequency].filter(Boolean).join(' · '),
        media,
      };
    },
  },
});
